<?php
/**
 * Based on CIS Technical Documents File: Appendix 03-21-2016.pdf
 * Experian/Fair Isaac Risk Models (6, 7, 8, 9, F, I, K, N, R, V, AA, AB, AC, AD, AE, AF, AG, AJ, F9, FE, FF)
 * Text/Adverse Action Reason"
 * Page No: 37
 */
$codeMap=[
	"01"=>"AMOUNT OWED ON ACCOUNTS IS TOO HIGH",
	"02"=>"LEVEL OF DELINQUENCY ON ACCOUNTS",
	"03"=>"TOO FEW BANK/NATIONAL REVOLVING ACCOUNTS",
	"04"=>"TOO MANY BANK/NATIONAL REVOLVING ACCOUNTS",
	"05"=>"TOO MANY ACCOUNTS WITH BALANCES",
	"06"=>"TOO MANY CONSUMER FINANCE COMPANY ACCOUNTS",
	"07"=>"ACCOUNT PAYMENT HISTORY IS TOO NEW TO RATE",
	"08"=>"TOO MANY INQUIRIES LAST 12 MONTHS",
	"09"=>"TOO MANY ACCOUNTS RECENTLY OPENED",
	"10"=>"RATIO OF BALANCE TO LIMIT ON BANK REVOLVING OR OTHER REV ACCTS TOO HIGH",
	"11"=>"AMOUNT OWED ON REVOLVING ACCOUNTS IS TOO HIGH",
	"12"=>"LENGTH OF TIME REVOLVING ACCOUNTS HAVE BEEN ESTABLISHED",
	"13"=>"TIME SINCE DELINQUENCY IS TOO RECENT OR UNKNOWN",
	"14"=>"LENGTH OF TIME ACCOUNTS HAVE BEEN ESTABLISHED",
	"15"=>"LACK OF RECENT BANK/NATIONAL REVOLVING INFORMATION",
	"16"=>"LACK OF RECENT REVOLVING ACCOUNT INFORMATION",
	"17"=>"NO RECENT NON-MORTGAGE BALANCE INFORMATION",
	"18"=>"NUMBER OF ACCOUNTS WITH DELINQUENCY",
	"19"=>"TOO FEW ACCOUNTS CURRENTLY PAID AS AGREED",
	"20"=>"TIME SINCE DEROGATORY PUBLIC RECORD OR COLLECTION IS TOO SHORT",
	"21"=>"AMOUNT PAST DUE TO ACCOUNTS",
	"22"=>"SERIOUS DELINQUENCY, DEROGATORY PUBLIC RECORD OR COLLECTION FILED",
	"24"=>"NO RECENT REVOLVING BALANCES",
	"25"=>"LENGTH OF TIME INSTALLMENT LOANS HAVE BEEN ESTABLISHED",
	"26"=>"NUMBER OF REVOLVING ACCOUNTS",
	"28"=>"NUMBER OF ESTABLISHED ACCOUNTS",
	"30"=>"TIME SINCE MOST RECENT ACCOUNT OPENING IS TOO SHORT",
	"31"=>"TOO FEW ACCOUNTS WITH RECENT PAYMENT INFORMATION",
	"32"=>"LACK OF RECENT INSTALLMENT LOAN INFORMATION",
	"33"=>"PROPORTION OF LOAN BALANCES TO LOAN AMOUNTS IS TOO HIGH",
	"34"=>"AMOUNT OWED ON DELINQUENT ACCOUNTS",
	"36"=>"LENGTH OF TIME OPEN INSTALLMENT LOANS HAVE BEEN ESTABLISHED",
	"37"=>"NUMBER OF FINANCE COMPANY ACCOUNTS ESTABLISHED RELATIVE TO LENGTH",
	"OF"=>"FINANCE HISTORY",
	"38"=>"SERIOUS DELINQUENCY AND PUBLIC RECORD OR COLLECTION FILED",
	"39"=>"SERIOUS DELINQUENCY",
	"40"=>"DEROGATORY PUBLIC RECORD OR COLLECTION FILED",
	"98"=>"LACK OF RECENT AUTO LOAN INFORMATION",
	"99"=>"LACK OF RECENT CONSUMER FINANCE COMPANY ACCOUNT INFORMATION"
];