<?php
/**
 * Based on CIS Technical Documents File: Appendix 03-21-2016.pdf
 * Experian/MDS Bankruptcy Model
 * Text/Adverse Action Reason"
 * Page No: 40
 */
$codeMap=[
	" A"=>"TOO FEW ACCOUNTS WITH SATISFACTORY RATINGS",
	" B"=>"PRESENCE OF DELINQUENT ACCOUNTS",
	" C"=>"PRESENCE OF DEROGATORY ACCOUNTS",
	" D"=>"ACCOUNTS WITH PAST-DUE BALANCES",
	" E"=>"TOO MANY CREDIT OBLIGATIONS",
	" F"=>"INSUFFICIENT CREDIT HISTORY ON NEW ACCOUNTS",
	" G"=>"AGE OF OLDEST REPORTED ACCOUNT",
	" H"=>"RECENTLY ACTIVE OR LACK OF BANK, RETAIL OR FINANCE ACCOUNTS",
	" I"=>"RATIO OF BALANCES TO TOTAL CREDIT LIMIT ON ALL ACCOUNTS",
	" J"=>"TOO FEW SATISFACTORY RATINGS FOR BANK REVOLVING ACCOUNTS",
	" K"=>"RATIO OF BANK REVOLVING BALANCES TO CREDIT LIMITS OR LACK OF BANK REVOLVING ACCOUNT INFORMATION",
	" L"=>"NEW BANK REVOLVING ACCOUNTS",
	" M"=>"PRESENCE OF BANK INSTALLMENT LOANS",
	" N"=>"INSUFFICIENT CREDIT HISTORY OR LACK OF BANK OR FINANCE ACCOUNTS",
	" O"=>"TOO FEW SATISFACTORY RATINGS ON RETAIL ACCOUNTS OR LACK OF RETAIL ACCOUNT INFORMATION",
	" P"=>"RATIO OF RETAIL REVOLVING BALANCES TO CREDIT LIMITS",
	" Q"=>"TOO FEW SATISFACTORY RATINGS ON FINANCE ACCOUNTS",
	" R"=>"INSUFFICIENT CREDIT HISTORY ON FINANCE ACCOUNTS",
	" S"=>"PRESENCE OF FINANCE ACCOUNTS",
	" T"=>"INSUFFICIENT CREDIT HISTORY ON NEWEST AUTO FINANCE ACCOUNT",
	" U"=>"PRESENCE OF AUTO FINANCE ACCOUNTS",
	" V"=>"LACK OF MORTGAGE OR REAL ESTATE ACCOUNTS WITH SATISFACTORY RATINGS",
	" W"=>"LACK OF OR INSUFFICIENT CREDIT HISTORY ON MORTGAGE OR REAL ESTATE ACCOUNTS",
	" X"=>"PRESENCE OF RECENT INQUIRIES",
	" Y"=>"NO ADVERSE ACTION (DISPLAYS ONLY IF NO OTHER SCORE FACTOR CODE IS GENERATED)",
	"5F"=>"PRESENCE OF INQUIRIES NEGATIVELY INPACTS THE SCORE"
];