<?php
/**
 *	Based on CIS Technical Documents File: Appendix 03-21-2016.pdf
 *	Section: F. Fraud Shield Indicators
 *	Page No: 82
 */
$fraudShieldIndicators=[
	'01'=> 'INQUIRY/ONFILE CURRENT ADDRESS CONFLICT',
	'02'=> 'INQUIRY ADDRESS 1ST REPORTED < 90 DAYS',
	'03'=> 'INQUIRY CURRENT ADDRESS NOT ONFILE',
	'04'=> 'INPUT SSN ISSUE DATE UNVERIFIED',
	'05'=> 'INQUIRY SSN RECORDED AS DECEASED',
	'06'=> 'INQUIRY AGE YOUNGER THAN SSN ISSUE DATE',
	'07'=> 'CREDIT ESTABLISHED BEFORE AGE 18',
	'08'=> 'CREDIT ESTABLISHED PRIOR TO SSN ISSUE DATE',
	'09'=> 'MORE THAN 3 INQUIRIES IN LAST 30 DAYS',
	'10'=> 'INQUIRY ADDRESS: ALERT',
	'11'=> 'INQUIRY ADDRESS: NON-RESIDENTIAL',
	'12'=> 'SECURITY STATEMENT PRESENT ON REPORT',
	'13'=> 'HIGH PROBABILITY SSN BELONGS TO ANOTHER',
	'14'=> 'INQUIRY SSN FORMAT IS INVALID',
	'15'=> 'INQUIRY ADDRESS: CAUTIOUS',
	'16'=> 'ONFILE ADDRESS: ALERT',
	'17'=> 'ONFILE ADDRESS: NON-RESIDENTIAL',
	'18'=> 'ONFILE ADDRESS: CAUTIOUS',
	'19'=> 'CURRENT ADDRESS RPT BY NEW TRADE ONLY',
	'20'=> 'CURRENT ADDRESS RPT BY TRADE OPEN<90 DAYS',
	'21'=> 'TELEPHONE NUMBER INCONSISTENT WITH ONFILE ADDRESS',
	'25'=> 'BEST ONFILE SSN RECORDED AS DECEASED',
	'26'=> 'BEST ONFILE SSN ISSUE DATE UNVERIFIED',
	'27'=> 'SSN REPORTED MORE FREQUENTLY FOR ANOTHER',
	'30'=> 'MORE AUTH USER TRADES THAN OTHER TRADES',
	'31'=> 'CURRENT ADDRESS REPORTED BY INQUIRY ONLY'
];